root:
- folders: ['controllers', 'libs', 'locale', 'medias', 'models', 'test', 'views']
- files: ['__init__.py']

controllers:
- folders: []
- files: ['__init__.py']

libs:
- folders: []
- files: ['__init__.py']

locale:
- folders: ['LC_MESSAGES']
- files: ['traduction.po']

medias:
- folders: ['css', 'js', 'img']
- files: []

models:
- folders: []
- files: ['__init__.py']

test:
- folders: []
- files: ['__init__.py']

views:
- folders: ['ajax', 'errors', 'static']
- files: []