title: framework-1
ndd: localhost
send_mail: 
recep_mail: 
timezone: Europe/Paris
lang: fr_FR
admin: admin/
mod_folder: modules
front_home: home
admin_home: home
home_page: main
home_class: main
memcache_time: 10
module_blacklist:
